parameters:
    candm_advancedform.form.type.mask_text.class: ClickAndMortar\AdvancedFormBundle\Form\MaskTextType

services:
    candm_advancedform.form.type.mask_text:
        class: '%candm_advancedform.form.type.mask_text.class%'
        tags:
            - { name: form.type, alias: candm_mask_text }